### ISSUE TITLE
Adding Arch Dynamis Lord and Warder of Courage

### ISSUE THREAD

**Issue by Headtatt** [xurion/ffxi-empy-pop-tracker#4]
Arch Dynamis Lord and Warder of Courage for your consideration.

[nms.zip](https://github.com/xurion/ffxi-empy-pop-tracker/files/4236875/nms.zip)

**Comment by xurion** [comment]
Thanks for this! I see a lot of people asking for an extension of NMs. It's a shame it was called EmpyPopTracker XD

Would you consider performing a PR?

**Comment by Headtatt** [comment]
Maybe? What's a PR? >.> I know my nub is showing :P

**Comment by xurion** [comment]
hehe no worries - I can implement it :)

**Comment by xurion** [comment]
The zip file you gave says it is invalid when I attempt to extract?

**Comment by Headtatt** [comment]
*grumble* you'd think it would let you load luas directly, let me see.
[adl.txt](https://github.com/xurion/ffxi-empy-pop-tracker/files/4240006/adl.txt)
[woc.txt](https://github.com/xurion/ffxi-empy-pop-tracker/files/4240007/woc.txt)

**Comment by xurion** [comment]
I have a separate branch for this for the time being. I've implemented both NMs, but I had to change some of the addon logic to accommodate ADL, as it uses regular items as pops rather than KIs. Without that change, the text area does not turn green once you have all the pops.

I updated the strings for each NM and/or location to keep them consistent with the other trackable NMs. I'm going to speak with the Windower guys about including this tomorrow.

https://github.com/xurion/ffxi-empy-pop-tracker/tree/dynamis-lord-and-woc

Thanks again!

**Comment by xurion** [comment]
@Headtatt what's you character name and server so I can drop you a credit for this. Thanks.

**Comment by Headtatt** [comment]
Headtatt on siren :)

**Comment by xurion** [comment]
This is now in Windower and should update next time you open the launcher!
https://github.com/Windower/Lua/pull/1834

Thanks again!
